### ISSUE TITLE
Cannot install package due to lack of setup.py

### ISSUE THREAD

**Issue by smy20011** [shunk031/training-free-structured-diffusion-guidance#5]
Hey, It seems that pip cannot install this package due to lack of setup.py.
Do you mind create one?
I found some resources that may helpful.
https://python-packaging-tutorial.readthedocs.io/en/latest/setup_py.html

**Comment by shunk031** [comment]
@smy20011 Hi, thank you for the comment. Because of `pyproject.toml` and `poetry.lock`, this package can be installed without `setup.py`. If you still get installation errors after trying the commands described in README.md, please provide your python environment (e.g., OS version, python version, etc.) and the error log.

**Comment by smy20011** [comment]
Can confirm it works.Thank you so much. It must due to some wired error in my conda config.
